version: '3'

tasks:
  run:
    cmds:
      - python3 -m http.server 8000 --directory app

  push:
    preconditions: 
      # test existence of modified files, grep will exit with a failure if there is no match
      - git ls-files -m -o | grep -E '.'
    #status:
    #  - git status
    cmds:
      - git add --all
      - git commit -m "app"
      - git push


  assets:
    cmds:
      - esbuild --bundle --minify css/index.css > public/bundle.css