version: '3'

tasks:
  default:
    cmds:
      - task --list-all
  run:
    cmds:
      - python3 -m http.server 8000 --directory app

  gcp:deploy:
    cmds:
      - gcloud run deploy 

  gcp:info:
   cmds:
     - gcloud run services list
     - gcloud run services describe backend

  push:
    preconditions: 
      # test existence of modified files, grep will exit with a failure if there is no match
      - sh: git ls-files -m -o | grep -E '.'
        msg: "nothing to do, no modified files"
    #status:
    #  - git status
    cmds:
      - git add --all
      - git commit -m "app"
      - git push